<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RuanganSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('ruangan')->insert([
            [
                'kode_ruangan' => 'KLS-7A',
                'nama_ruangan' => 'Kelas 7A',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 1',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-7B',
                'nama_ruangan' => 'Kelas 7B',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 1',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-7C',
                'nama_ruangan' => 'Kelas 7C',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 1',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-8A',
                'nama_ruangan' => 'Kelas 8A',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 2',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-8B',
                'nama_ruangan' => 'Kelas 8B',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 2',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-8C',
                'nama_ruangan' => 'Kelas 8C',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 2',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-9A',
                'nama_ruangan' => 'Kelas 9A',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 3',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-9B',
                'nama_ruangan' => 'Kelas 9B',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 3',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KLS-9C',
                'nama_ruangan' => 'Kelas 9C',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMP',
                'lokasi' => 'Lantai 3',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'RPL-X',
                'nama_ruangan' => 'RPL X',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan RPL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'RPL-XI',
                'nama_ruangan' => 'RPL XI',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan RPL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'RPL-XIIA',
                'nama_ruangan' => 'RPL XIIA',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan RPL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'RPL-XIIB',
                'nama_ruangan' => 'RPL XIIB',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan RPL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'BDP-X',
                'nama_ruangan' => 'BDP X',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan BDP',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'BDP-XI',
                'nama_ruangan' => 'BDP XI',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan BDP',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'BDP-XII',
                'nama_ruangan' => 'BDP XII',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan BDP',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'AKL-X',
                'nama_ruangan' => 'AKL X',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan AKL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'AKL-XI',
                'nama_ruangan' => 'AKL XI',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan AKL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'AKL-XII',
                'nama_ruangan' => 'AKL XII',
                'jenis_ruangan' => 'kelas',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => 'Jurusan AKL',
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KTR-OFC',
                'nama_ruangan' => 'Kantor Office',
                'jenis_ruangan' => 'kantor',
                'unit' => 'UMUM',
                'lokasi' => 'Gedung Utama',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KTR-GRU-2',
                'nama_ruangan' => 'Kantor Guru Lantai 2',
                'jenis_ruangan' => 'kantor',
                'unit' => 'UMUM',
                'lokasi' => 'Lantai 2',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KTR-GRU-3',
                'nama_ruangan' => 'Kantor Guru Lantai 3',
                'jenis_ruangan' => 'kantor',
                'unit' => 'UMUM',
                'lokasi' => 'Lantai 3',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'KTR-KPS',
                'nama_ruangan' => 'Kantor Kepala Sekolah',
                'jenis_ruangan' => 'kantor',
                'unit' => 'UMUM',
                'lokasi' => 'Gedung Utama',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'LAB-SMP',
                'nama_ruangan' => 'Lab Komputer SMP',
                'jenis_ruangan' => 'laboratorium',
                'unit' => 'SMP',
                'lokasi' => 'Gedung SMP',
                'keterangan' => null,
                'status' => 'aktif',
            ],
            [
                'kode_ruangan' => 'LAB-SMK',
                'nama_ruangan' => 'Lab Komputer SMK',
                'jenis_ruangan' => 'laboratorium',
                'unit' => 'SMK',
                'lokasi' => 'Gedung SMK',
                'keterangan' => null,
                'status' => 'aktif',
            ],
        ]);
    }
}
